### ISSUE TITLE
Introduce duplicate handling

### ISSUE THREAD

**Issue by fabkel** [stayhomech/stayhomech#176] opened 2020-04-06 13:15 UTC
potential duplicates could be shown together or highlighted or it could be a separate menu point.

you could find them by comparing email addresses or URLs.

this is because apparently people have entered their business in more than one page that we are getting data from
-> could be a growing problem

**Comment by mageo** [comment] 2020-04-06 17:46
Duplicate of #131

**Closed as completed by mageo** 2020-04-06 17:46 UTC
Labels: enhancement
